project:
  type: website
  output-dir: docs

website:
  sidebar:
    contents:
      - section: "Basic Analysis"
        contents:
          - href: index.qmd
      - section: "More Stuff"
        contents:
          - href: section1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

