project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "John Humphreys"
  page-footer:
    left: "&copy; Copyright 2022, John Humphreys"
    right: "Under Construction"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: contact me
        menu:
          - icon: github
            href: https://github.com/JMHumphreys
            text: "jmhumphreys"
          - favicon: osf.svg
            href: https://osf.io/zwbhm/
            text: "John M Humphreys"
          - icon: google
            href: https://scholar.google.com/citations?hl=en&user=rLUtjhgAAAAJ
            text: "John M Humphreys"
          - icon: lightbulb
            href: https://orcid.org/0000-0002-8464-0886
            text: "ORCID"
          - icon: envelope
            href: mailto:jmh09r@my.fsu.edu
            text: "jmh09r@my.fsu.edu"
      - href: section1.qmd
        text: projects
      - href: section2.qmd
        text: about
        
#website:
#  sidebar:
#    contents:
#      - section: "Basic Analysis"
 #       contents:
 #         - href: index.qmd
 #     - section: "More Stuff"
 #       contents:
#          - href: section1.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

