project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "John Humphreys"
  page-footer:
    left: "&copy; Copyright 2022, John Humphreys"
    right: "Under Construction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd
        text: Projects
      - href: section1.qmd
        text: About
        
#website:
#  sidebar:
#    contents:
#      - section: "Basic Analysis"
 #       contents:
 #         - href: index.qmd
 #     - section: "More Stuff"
 #       contents:
#          - href: section1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

