project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  page-navigation: true
  title: "Spatial Lab"
  open-graph: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: section1.qmd
        text: Research
      - href: about.qmd
        text: About
      - text: Connect
        menu:
          - icon: github
            href: https://github.com/JMHumphreys
            text: "jmhumphreys"
          - icon: octagon
            href: https://osf.io/zwbhm/
            text: "John M Humphreys"
          - icon: google
            href: https://scholar.google.com/citations?hl=en&user=rLUtjhgAAAAJ
            text: "John M Humphreys"
          - icon: lightbulb
            href: https://orcid.org/0000-0002-8464-0886
            text: "ORCID"
          - icon: envelope
            href: mailto:jmh09r@my.fsu.edu
            text: "jmh09r@my.fsu.edu"
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/JMHumphreys/jmhumphreys.github.io
          - text: Report a Bug
            url:  https://github.com/JMHumphreys/jmhumphreys.github.io/issues
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v1.2.335"
    right: "© 2023 [John Humphreys](/about) | [MIT License](/license)"
        
#website:
#  sidebar:
#    contents:
#      - section: "Basic Analysis"
 #       contents:
 #         - href: index.qmd
 #     - section: "More Stuff"
 #       contents:
#          - href: section1.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

